# pyproject.toml
[tool.black]
line-length = 88
exclude = '''
/(
    \.venv/
  | migrations/
  | __pycache__/
  | \.vscode/
  | \.pytest_cache/
  | \.coverage
)/
'''

[tool.isort]
profile = "black"
skip = [".venv", "migrations", ".vscode",".pytest_cache",".coverage"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["ci_cd", "brief_app", "project-wide-tests"]