version: '3.8'

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY: ${SECRET_KEY}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"