version: '3.8'

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    command: ["/bin/bash", "-c", "./ci_cd/scripts/docker/entrypoint.sh"]
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"