name: CD Pipeline

on:
  workflow_call:
    secrets:
      RENDER_API_TOKEN:
        required: true
      IMAGE_TAG:
        required: true
      DATABASE_URL:
        required: true
      SECRET_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set lowercase repository name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy to Render
        env:
          REPO_LC: ${{ env.REPO_LC }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          chmod +x ./src/ci_cd/shell/deploy.sh
          ./src/ci_cd/shell/deploy.sh
