name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      # Uncomment the following steps when ready to build and deploy

      # - name: Build Docker image
      #   run: |
      #     docker build -t my-app:latest .

      # - name: Push Docker image to registry
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #     docker tag my-app:latest my-docker-repo/my-app:latest
      #     docker push my-docker-repo/my-app:latest

      # - name: Deploy to Railway or Render
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      #     RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      #   run: |
      #     # Example for Railway
      #     railway up
      #     # Example for Render
      #     curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" \
      #       -H "Content-Type: application/json" \
      #       -d '{"serviceId": "your-service-id", "branch": "main"}' \
      #       https://api.render.com/v1/deploys