name: CD Pipeline

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Log in to GitHub Container Registry
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy to Render
        run: |
          chmod +x ./src/ci_cd/shell/deploy.sh
          ./src/ci_cd/shell/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          REPO_LC: ${{ env.REPO_LC }}
          IMAGE_TAG: ${{ github.sha }}
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}